### ISSUE TITLE
u_long not defined on Windows

### ISSUE THREAD

**Issue by tinne26** [airwindows/Meter#7]
Hey, this is only an issue trying to help a little with the compilation issues. If it ends up not being helpful, feel free to dismiss it and close it.

I took a look at the output of the most recent github action run (https://github.com/airwindows/Meter/actions/runs/8675202868/job/23788366785). While logged into github, you can click on the "Windows" job on the left side, and pressing on the failing build task shows the relevant output:

![ulong](https://github.com/airwindows/Meter/assets/95440833/223c64bc-c893-47a8-89de-2211bbb0a5a9)

It looks like `u_long` must be a type alias, probably for `unsigned long`, that's defined somewhere in the linux environment / header files, but not on Windows. I assume either changing to `unsigned long` everywhere or adding a typedef for Windows would resolve the issues on that platform.

Linux tests are also failing due to some `bad_alloc` errors, which can be viewed in the same way through the github UI. Well, I assume you will be able to see it, I appended the screenshot just in case as it's a beta feature and there's a small chance it might not be available on your account / region.

Everything else seems to be set up properly, so if the build and test issues are solved, the generated artifacts / binaries should also appear at the end of the github workflow job window. That's all I can do without actually installing the dependencies and testing locally, but I hope something of what I mentioned can help, even if only a little bit. Otherwise we will keep investigating!

**Comment by airwindows** [comment]
Worth a try! I've replaced it with 'int' as I know the number is always going to fit inside int. If we're going to be casting an integer to whatever that array value is, I see no reason to pick something unusual. I don't know what bad_alloc errors are :)

**Comment by tinne26** [comment]
Windows is building now, and it's only tests that are failing, so let's close this issue!
